<?php
/**
 * 登录控制
 * @author mybsdc <mybsdc@gmail.com>
 * @date 2017/8/1
 * @time 8:37
 */

namespace app\home\controller;

use think\Controller;

class Login extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = model('User');
    }

    /**
     * 登录页面
     * @return mixed
     */
    public function index()
    {
        return $this->fetch('login/index');
    }

    /**
     * 处理登录请求
     * @return \think\response\Json
     */
    public function doLogin()
    {
        $email = input('post.email');
        $pwd = input('post.pwd');

        if (!$email) {
            return json(['code' => -1, 'tips' => '请输入邮箱']);
        }

        if(!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            return json(['code' => -1, 'tips' => '请输入一个正确的邮箱地址']);
        }

        if (!$pwd) {
            return json(['code' => -1, 'tips' => '请输入密码']);
        }

        if (!$this->user->haveEmail($email)) {
            return json(['code' => -1, 'tips' => '该邮箱不存在']);
        }

        $result = $this->user->checkUser($email, $pwd);
        if (!$result) {
            return json(['code' => -1, 'tips' => '密码错误']);
        } else {
            session('user.id', $result['id']);
            session('user.name', $result['name']);
            session('user.is_admin', $result['is_admin']);
            return json(['code' => 200, 'tips' => '登录成功']);
        }
    }

    // 登出
    public function logout()
    {
        session('user.id', null);
        session('user.name', null);
        session('user.is_admin', null);
        return $this->redirect('home/Login/index');
    }
}