<?php
/**
 *                                  _oo0oo_
 *                                 088888880
 *                                 88" . "88
 *                                 (| -_- |)
 *                                  0\ = /0
 *                               ___/'---'\___
 *                             .' \\|     |// '.
 *                            / \\|||  :  |||// \
 *                           /_ ||||| -:- |||||- \
 *                          |   | \\\  -  /// |   |
 *                          | \_|  ''\---/''  |_/ |
 *                          \  .-\__  '-'  __/-.  /
 *                        ___'. .'  /--.--\  '. .'___
 *                     ."" '<  '.___\_<|>_/___.' >'  "".
 *                    | | : '-  \'.;'\ _ /';.'/ - ' : | |
 *                    \  \ '_.   \_ __\ /__ _/   .-' /  /
 *                ====='-.____'.___ \_____/___.-'____.-'=====
 *                                  '=---='
 *
 *
 *              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 *                           佛主保佑  iii  永无BUG
 * 所有控制器基类
 * @author mybsdc <mybsdc@gmail.com>
 * @date 2017/7/23
 * @time 22:14
 */

namespace app\home\controller\common;

use think\Controller;
use think\Request;

class Base extends Controller
{
    protected $url;

    // 无需登录即可访问的控制器方法
    protected $allowView = [
        'home/login/index',
        'home/error/index',
    ];

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user_role = model('UserRole');
        $this->role_access = model('RoleAccess');
        $this->access = model('Access');

        // 当前访问地址path_info
        $this->url = Request::instance()->path();

        // 验证登录与否
        if (!session('?user.id') && !in_array($this->url, $this->allowView)) {
            $this->redirect('home/login/index');
            return false;
        }

        /**
         * 权限验证
         * 逻辑：取出当前登录用户所属角色 => 取出所属角色的对应权限 => 取出所有权限对应的url => 判断当前路径是否在所有权限路径之中
         */
//        p($this->url);
//        p($this->checkAccess($this->url));
        if (!$this->checkAccess($this->url)) {
            $this->redirect('home/error/index');
            return false;
        }
    }

    /**
     * 检查是否有权访问当前url
     * @param string $url
     * @return bool
     */
    public function checkAccess($url = '')
    {
        if (session('user.is_admin')) { // 若是超级管理员
            return true;
        }

        if (in_array(Request::instance()->path(), $this->allowView)) { // 若当前页面无需权限访问
            return true;
        }

        return in_array($url, $this->getUserAllAccess());
    }

    /**
     * 获取当前用户有权限访问的所有url
     * @param int $uid
     */
    public function getUserAllAccess($uid = 0)
    {
        if (!$uid) {
            $uid = session('user.id');
        }

        $links = [];
        $roleIdList = $this->user_role->getUserAllRole($uid); // 取出当前用户所有角色id
        if ($roleIdList) {
            $accessIdList = $this->role_access->getRoleAllAccess($roleIdList); // 取出角色对应的所有权限id

            // 取出所有的权限链接
            if ($accessIdList) {
                $links = $this->access->getAllAccessLink($accessIdList);
            }
        }
        return $links;
    }
}